service: rick-and-morty-api
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  getCharacters:
    handler: src/controllers/getCharacters.getCharacters
    events:
      - httpApi:
          path: /characters
          method: get
  createCharacter:
    handler: src/controllers/createCharacter.createCharacter
    events:
      - httpApi:
          path: /characters
          method: post 